### ISSUE TITLE
Enhance GUI

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#1]
modify the boring interface

**Comment by aksh1009** [comment]
I would like to work on the issue under JWOC

**Comment by Pankaj0038** [comment]
okay @aksh1009

**Comment by Pankaj0038** [comment]
@aksh1009 share your progress till now

**Comment by Pankaj0038** [comment]
@aksh1009 24 hours given to you to submit 
do it asap

**Comment by daksh1210jain** [comment]
sir i would like to try to work on this issue under JWOC
can you also guide me a bit so that i can work on it a bit better

**Comment by Pankaj0038** [comment]
okay @daksh1210jain 

you can go through this videos to modify the gui

hover button : https://www.youtube.com/watch?v=fKFpxud0O6c

rounded button with edges : https://www.youtube.com/watch?v=Xv57jB_Xvqo

you can place logo in the decoder : https://www.youtube.com/watch?v=YDp73WjNISc&t=362s

can modify theme and input field : https://www.youtube.com/watch?v=ah3JeHAfM0M

**Comment by daksh1210jain** [comment]
Ok sir surely I will try my best
