### ISSUE TITLE
add Atbash cipher encoder/decoder 

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#17]
atbash cipher : https://en.wikipedia.org/wiki/Atbash

**Comment by daksh1210jain** [comment]
Kindly assign me this issue  under JWOC tag

**Comment by Pankaj0038** [comment]
Okay @daksh1210jain

**Comment by daksh1210jain** [comment]
I have created a PR #23 
Kindly review it and accept it

**Comment by Pankaj0038** [comment]
Check the pr comments
