### ISSUE TITLE
create an input field for key values

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#18]
the code will receive key values from this input field 
It will use the key when its needed otherwise it just clear the field

**Comment by SGCODEX** [comment]
Above the text taking input part?

**Comment by Pankaj0038** [comment]
in between the text input field and buttons

**Comment by SGCODEX** [comment]
I would like to work on this issue under JWOC

**Comment by Pankaj0038** [comment]
@SGCODEX submit the xor decoder first

**Comment by Pankaj0038** [comment]
okay @SGCODEX

**Comment by SGCODEX** [comment]
Bhaiya can we make another issue for XOR key thing after this (so that we can use this key value from here now)? (Good opportunity for me to gain some points hehe)

**Comment by Pankaj0038** [comment]
Okay @SGCODEX you can create an issue after this ,

**Comment by SGCODEX** [comment]
PR incoming bhaiya .. :)
