### ISSUE TITLE
Add more encoding algorithms

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#2]
add algorithms in the encoders folder and add the corresponding button in kvlang file

**Comment by Shrutakeerti** [comment]
hi @Pankaj0038 , pls assign me this issue i want to contribute in this

**Comment by Pankaj0038** [comment]
hello @Shrutakeerti , Sorry I cannot assign it to you right now , 
Kindly comment after 15 th Jan , (when the coding phase starts)

**Comment by daksh1210jain** [comment]
hi @Pankaj0038 , pls assign me this issue i want to contribute in this under JWOC tag

**Comment by Pankaj0038** [comment]
You can contribute one issue at a time on a project

**Comment by Shrutakeerti** [comment]
hi @Pankaj0038 , pls assign me this issue i want to contribute in this under JWOC

**Comment by Pankaj0038** [comment]
@Shrutakeerti okay

**Comment by Pankaj0038** [comment]
@Shrutakeerti give update about your progress

**Comment by Shrutakeerti** [comment]
hi @Pankaj0038 I am currently working on the python code from the kivy app for cfeating algoritmic files in the encoders

**Comment by Pankaj0038** [comment]
okay @Shrutakeerti but you need to submit it before tomorrow

**Comment by Pankaj0038** [comment]
@Shrutakeerti you need to submit it asap , its already over a day 
I cannot give you more time
submit before 4 pm or I will assign this issue to others

**Comment by Pankaj0038** [comment]
sorry @Shrutakeerti but I cannot give you more time

**Comment by amrikhore86** [comment]
I am interested in working on this issue

**Comment by Pankaj0038** [comment]
okay @amrikhore86

**Comment by Pankaj0038** [comment]
@amrikhore86 add jwoc keyword in your comment
