### ISSUE TITLE
Spelling error in dcodeki.py

### ISSUE THREAD

**Issue by SGCODEX** [Pankaj0038/dcodeKi#20]
![2error](https://github.com/Pankaj0038/dcodeKi/assets/64886313/e9accac6-a64e-407f-a857-f71f890a449f)

Binary Spelling is wrong, I would like to raise and solve this issue under JWOC

**Comment by Pankaj0038** [comment]
@SGCODEX  it won't help you to learn 
work on the other issue (key-input)

**Comment by SGCODEX** [comment]
okay bhaiya :)
