### ISSUE TITLE
add Search functionality

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#22]
add search bar + button 
when clicked it will either add one more section to show the particular button (related to the search) or hide all other button except the search related

**Comment by SGCODEX** [comment]
I want to work on this issue after XOR Key Issue under JWOC

**Comment by Pankaj0038** [comment]
okay finish the other one first

**Comment by SGCODEX** [comment]
finished bhaiya, please assign this issue to me under JWOC

**Comment by Pankaj0038** [comment]
okay assigning you but edit your comment and mention JWOC

**Comment by SGCODEX** [comment]
done bhaiya

**Comment by Pankaj0038** [comment]
@SGCODEX while creating the search functionality you can add [kivyMDicon](https://kivymd.readthedocs.io/en/latest/themes/icon-definitions/) button (for search button) 
that looks better than a normal text-button

**Comment by SGCODEX** [comment]
Sure bhaiya, just caught in a deadline of college, will hopefully submit the PR by tommorow

**Comment by Pankaj0038** [comment]
@SGCODEX approximately 24 hours left for this issue

**Comment by Pankaj0038** [comment]
sorry @SGCODEX , can't give you more time

**Comment by viendimine** [comment]
pls assign me this issue under "JWOC"

**Comment by Pankaj0038** [comment]
Okay @vishapraj

**Comment by Pankaj0038** [comment]
@vishapraj update your progress

**Comment by Pankaj0038** [comment]
@vishapraj cannot give you more time

**Comment by Bishal-35** [comment]
I would like to work on it under JWoC'24

**Comment by Pankaj0038** [comment]
Okay @Bishal-35
