### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#27]
Every time when an error occur  the program stop running , 
Your task is to fix this , I mean you need to make it able to run after an exception also

(exception are like : wrong input data (needed binary but given anything else) , functionality error , edge cases etc)

**Comment by SGCODEX** [comment]
Bhaiya was the str not callable error part of this only? :)
![Screenshot 2024-01-16 012625](https://github.com/Pankaj0038/dcodeKi/assets/64886313/345c1fa4-eb4d-4fc3-8f0f-341014103267)
If yes so solved this in the issue in requested pr #28

**Comment by Pankaj0038** [comment]
nah actually not
you need to make it to continue to run even after an exception

**Comment by SGCODEX** [comment]
We can use try block... but tag easy is just so less rewarding for it 😂😂

**Comment by Pankaj0038** [comment]
you just need to add the try-catch block , that is not a big deal  
I know you can do it easily

**Comment by SGCODEX** [comment]
okay bhaiya, after search bar will be on it :)

**Comment by Pankaj0038** [comment]
okay but finish the search bar first , 
if nobody till then comment under it I will assign it to you

**Comment by SGCODEX** [comment]
Yes Bhaiya

**Comment by ayushmorbar** [comment]
Hey 👋,
I want to work on this issue as part of JWoC!

**Comment by Pankaj0038** [comment]
Okay @ayushmorbar

**Comment by ayushmorbar** [comment]
On it.

**Comment by ayushmorbar** [comment]
Hey, wondering as if we're handling the errors in this code so should we use the 'logging module' to track the error logs.

**Comment by Pankaj0038** [comment]
ya you can use that

**Comment by Pankaj0038** [comment]
@ayushmorbar submit your task asap

**Comment by ayushmorbar** [comment]
> @ayushmorbar submit your task asap

Please do refer #74
