### ISSUE TITLE
Create a loading (Splash) screen

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#29]
a loading screen with the tool's name "dcodeKi"  might be okay , but if you want to add more on this then go for it

**Comment by daksh1210jain** [comment]
sir please assign me this issue under JWOC

**Comment by Pankaj0038** [comment]
okay @daksh1210jain

**Comment by Pankaj0038** [comment]
@daksh1210jain its already 3 days 
I cannot give you more time , submit it before 1 PM today

**Comment by Pankaj0038** [comment]
Sorry @daksh1210jain I cannot give you more time

**Comment by unknown-already-taken** [comment]
Hello @Pankaj0038, I would like to give it a try.

**Comment by Pankaj0038** [comment]
Ya , sure @sukriti-kuila

**Comment by unknown-already-taken** [comment]
How does this splash screen design look? Is it okay?
<img width="336" alt="image" src="https://github.com/Pankaj0038/dcodeKi/assets/87015685/9507b6c6-897b-4546-9063-49defaa13bfd">

**Comment by Pankaj0038** [comment]
is it a static image or you used any gif or video ? @sukriti-kuila

**Comment by unknown-already-taken** [comment]
static image

**Comment by Pankaj0038** [comment]
okay that's fine

**Comment by Pankaj0038** [comment]
well done @sukriti-kuila
