### ISSUE TITLE
Create copy to clipboard button

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#3]
I initialized the copy to clipboard function for every time it decodes or encodes and the output text cannot be select. Your task will be changing the functionality to optional , 
 ***you need to create a copy to clipboard button***

**Comment by aksh1009** [comment]
I would like to work on the issue under JWOC

**Comment by Pankaj0038** [comment]
@aksh1009 you can contribute one issue at a time , complete the other one then I can assign you this one

**Comment by k3s1** [comment]
assign me this issue under JWOC

**Comment by Pankaj0038** [comment]
@k3s1 your previous code on vigenere cipher have some flaws , work on them first

**Comment by daksh1210jain** [comment]
sir please assign me this issue under JWOC

**Comment by Pankaj0038** [comment]
complete the splash screen task first

**Comment by basedBaba** [comment]
Hello! I would like to work on this issue under JWOC.

**Comment by Pankaj0038** [comment]
okay @basedBaba
