### ISSUE TITLE
add rot8000 and octal conversion 

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#31]
[rot8000](https://www.dcode.fr/rot8000-cipher) : 
       encoding = character (ascii value of character + 31753 )
       decoding = character (ascii of the character - 31753)

octal : 
        character --> ascii of character --> space separated octal values

**Comment by basedBaba** [comment]
Hello! I would like to work on this issue under JWOC.

**Comment by Pankaj0038** [comment]
Okay @basedBaba
