### ISSUE TITLE
Create scroll bar and nav bar

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#33]
scroll bar for button only 
nav bar containing minimum 2 sections : algorithmic cipher , symbol cipher

**Comment by jack-a129** [comment]
I would like to work on this issue.

**Comment by Pankaj0038** [comment]
okay @jack-a129 , all the best

**Comment by Pankaj0038** [comment]
sorry jack , are you a participant of jwoc ? @jack-a129

**Comment by Pankaj0038** [comment]
@jack-a129

**Comment by jack-a129** [comment]
Sorry, I don't know what jwoc is

**Comment by jack-a129** [comment]
I am probably not participating in jwoc

**Comment by Pankaj0038** [comment]
okay you can work on this

**Comment by jack-a129** [comment]
I hope jwoc can tell me what it is.

**Comment by Pankaj0038** [comment]
Its actually a open source contribution contest organised by JGEC (Jalpaiguri Government Engineering College) for all , and I submitted this repo to JWoC for contribution

**Comment by jack-a129** [comment]
Thank you.

**Comment by Pankaj0038** [comment]
There all the participants need to contribute in the selected projects to gain score like this one was of 3 points medium challenge 

you can also take part and contribute to others
here is the link
https://www.jwoc.tech/

**Comment by jack-a129** [comment]
I feel bad that it is going to take a few days to resolve the issue while other issues are being resolved quickly!

**Comment by jack-a129** [comment]
It would be nice to know how a button-only scrollbar differs from a regular scrollbar.

**Comment by Pankaj0038** [comment]
You need to create scroll bar for the buttons only

Don't need to scroll the input field or labels

**Comment by jack-a129** [comment]
Thank you

**Comment by jack-a129** [comment]
If you don't mind, could you please tell me which algorithm is a symbol cipher?

**Comment by Pankaj0038** [comment]
there is no particular algorithm actually 
A symbol cipher contains some symbolic character that represent particular letter 
like you can check out the list given in dcode : https://www.dcode.fr/symbols-ciphers

**Comment by jack-a129** [comment]
I have completed the scroll bar for now.
Sorry for all the questions, but what should be included in the algorithmic cipher section and the symbol cipher section?

**Comment by Pankaj0038** [comment]
Everything till now will be in algorithmic section and will add later in symbol cipher section

**Comment by jack-a129** [comment]
thank you
