### ISSUE TITLE
add XOR bruteforce and rot13 brutefroce + few modification

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#34]
Changes to be done: 

1. XOR brute force = xor the text with the keys 01 to 255 and print cipher for each keys
2. rot13 brute force = 26 character set but shift 1 time to 25 times
3. add scroll bar at the output section , show 3-4 cipher at a time and to see more need to scroll
4. move copy to clip board button near the outputs , thus the user can copy any of the outputs

**Comment by Hacxmr** [comment]
Hey! @Pankaj0038  I am interested in working on this issue. Can you assign me this under JWOC'24

**Comment by Pankaj0038** [comment]
yeah sure @Hacxmr

**Comment by Pankaj0038** [comment]
@Hacxmr update about your progress

**Comment by Hacxmr** [comment]
@Pankaj0038 I am working on it

**Comment by Pankaj0038** [comment]
@Hacxmr read all the requirements first

**Comment by Pankaj0038** [comment]
> Changes to be done:
> 
>     1. XOR brute force = xor the text with the keys 01 to 255 and print cipher for each keys
> 
>     2. rot13 brute force = 26 character set but shift 1 time to 25 times
> 
>     3. add scroll bar at the output section , show 3-4 cipher at a time and to see more need to scroll
> 
>     4. move copy to clip board button near the outputs , thus the user can copy any of the outputs

**Comment by Hacxmr** [comment]
yes! @Pankaj0038 I'm still working

**Comment by SohanRC** [comment]
@Pankaj0038 I would like to work in this issue !!  Please assign me under JWOC 2024.

**Comment by Pankaj0038** [comment]
@Hacxmr update your progress
