### ISSUE TITLE
design a logo and add fav icon

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#35]
it will helpful if you create png format image file for logo and size 256 x 256 pixels

**Comment by swetasingh8844** [comment]
@Pankaj0038 please assign me this issue under jwoc'24

**Comment by Pankaj0038** [comment]
Okay @swetasingh8844

**Comment by swetasingh8844** [comment]
@Pankaj0038 I am unable to add  fav icon

**Comment by Pankaj0038** [comment]
Is your design ready ? @swetasingh8844

**Comment by Pankaj0038** [comment]
Okay thanks for your effort 😇 @swetasingh8844
