### ISSUE TITLE
Enhance readability of the code and update markdown file

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#36]
Add comment on the code (including algorithms)

Edit the variable names such that new users can understand

In markdown section add requirements that are not mentioned like kivyMD 

Difficulty level may upgrade depending upon your work

**Comment by daksh1210jain** [comment]
sir i would like to try to do this 
My apologies for my inability to do the previous task but I would like to try again

**Comment by Pankaj0038** [comment]
okay @daksh1210jain 
sorry if I discourage you , hoping for better outcome 
all the best

**Comment by daksh1210jain** [comment]
Not at all sir 
Thankyou

**Comment by Pankaj0038** [comment]
@daksh1210jain  one more thing I didn't use any external module for encoding algorithms so remove that from readme file 
and try to run the code and add screenshot to describe about the program if having any trouble with that then use this images
![Screenshot_2024-01-20_23_51_42](https://github.com/Pankaj0038/dcodeKi/assets/98003893/6c3d8537-90cc-4005-b1ed-740763df1299)
![Screenshot_2024-01-20_23_51_29](https://github.com/Pankaj0038/dcodeKi/assets/98003893/b3415548-01ed-4160-af51-3c715d3ad8d6)
![Screenshot_2024-01-20_23_51_19](https://github.com/Pankaj0038/dcodeKi/assets/98003893/2f1611bc-481a-4575-9b56-11be68d69bc3)
![Screenshot_2024-01-20_23_51_06](https://github.com/Pankaj0038/dcodeKi/assets/98003893/c7e24a95-6049-4d34-b891-34039cbbf36a)
