### ISSUE TITLE
add binary to text decoder

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#4]
convert binary string to decimal numbers and convert it to text message (according to the ASCII number)

for space separated binary string
example: "01101000 01100101 01101100 01101100 01101111"   -->  104,101,108,108,111 --> hello
                      104         101            108           108              111

for non-space separated binary string (separate them into 8 bit binary first)
example: "0110100001100101011011000110110001101111" --> 104,101,108,108,111 --> hello

**Comment by k3s1** [comment]
assign this issue to me under JWOC

**Comment by Pankaj0038** [comment]
okay @k3s1
