### ISSUE TITLE
Reverse text , upper case convertion , lowercase convertion 

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#42]
reverse :
     text = txet
upper case : 
    Haha1 = HAHA1
lowercase: 
   DcodeKi2 = dcodeki2

**Comment by daksh1210jain** [comment]
i want to work on this issue

**Comment by daksh1210jain** [comment]
under JWOC

**Comment by Pankaj0038** [comment]
you need to do few more work on the previous task

**Comment by Pankaj0038** [comment]
okay @daksh1210jain I'm assigning you this one but remember one thing this time I won't merge your pr unless I'm satisfied your code 
and try to make easily readable code

**Comment by daksh1210jain** [comment]
yes sir 
please tell that we have to add buttons like encoding buttons for performing the above operations?

**Comment by Pankaj0038** [comment]
Yes that is necessary
