### ISSUE TITLE
Add Leet (leet_speak) or 1337 encoder

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#44]
[leet](https://en.wikipedia.org/wiki/Leet) : 
         Greek = Gr33k
         Hacker = H4ck3r

**Comment by daksh1210jain** [comment]
I want to work on this issue under JWOC

**Comment by daksh1210jain** [comment]
sir i am interested in contributing to the issue

**Comment by sayan-ay** [comment]
I want to work on this
JWOC

**Comment by Pankaj0038** [comment]
okay @sayan-ay

**Comment by Pankaj0038** [comment]
@sayan-ay it's been 4 days , update about your progress

**Comment by sayan-ay** [comment]
> @sayan-ay it's been 4 days , update about your progress

Yeah I am working on it, will be ready by tomorrow

**Comment by ayushmorbar** [comment]
Please assign me this issue as well as part of JWoC.
