### ISSUE TITLE
Base45 and base62 encoder decoder

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#45]
base62 : 
resource : https://en.wikipedia.org/wiki/Base62
                 https://www.dcode.fr/base62-encoding
character set = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

base45 : 
resource: https://www.dcode.fr/base45-encoding
character set = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ" ," "(space),$,%,*,'+'(plus sign),'-'(minus sign),'.'(dot/full stop) , '/'(forward slash), ':' (colon)"

**Comment by Hacxmr** [comment]
Hey! @Pankaj0038 I am interested in working on this issue

**Comment by Pankaj0038** [comment]
are you a participant of JWoC ?
Okay you need to add JWoC keyword while asking for assignment , and can do at most 1 issue per project at a time

**Comment by AnamNaaz-7** [comment]
Please assign this issue to me under  JWOC.

**Comment by Pankaj0038** [comment]
okay @AnamNaaz-7

**Comment by yashasvini121** [comment]
Hey @Pankaj0038. Can you please assign me this issue under JWOC'24?

**Comment by Pankaj0038** [comment]
okay @yashasvini121
