### ISSUE TITLE
add fav icon

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#46]

**Comment by daksh1210jain** [comment]
sir can you explain me about this issue

**Comment by daksh1210jain** [comment]
i am interested to know about it

**Comment by Pankaj0038** [comment]
Ya sure
Description: https://en.m.wikipedia.org/wiki/Favicon

Tutorial to change fav icon : https://youtu.be/yKgN7iT8w0E?si=vAQPJZU6ZqPbyk3i

**Comment by Pankaj0038** [comment]
Add comment that you want to contribute under JWoC otherwise I cannot merge your pr @daksh1210jain

**Comment by daksh1210jain** [comment]
I want to contribute under JWOC

**Comment by Pankaj0038** [comment]
okay @daksh1210jain
