### ISSUE TITLE
URL encoding + decoding

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#48]
URL encoding or percent encoding
helpful resource : https://en.wikipedia.org/wiki/Percent-encoding

**Comment by rakesh-paulraj** [comment]
i would like to work on this under jwoc

**Comment by Pankaj0038** [comment]
okay @rakesh-paulraj

**Comment by rakesh-paulraj** [comment]
SORRY TO SAY THIS PLEASE DE ASSIGN IT TO SOMEONE ELSE

**Comment by rakesh-paulraj** [comment]
SORRY TO SAY THIS PLEASE DE ASSIGN IT TO ME M AND ASSIGN IT TO SOMEONE ELSE

**Comment by Pankaj0038** [comment]
okay @rakesh-paulraj

**Comment by pranjalipilankar** [comment]
I would like to work on this under JWOC

**Comment by Pankaj0038** [comment]
okay @pranjalipilankar

**Comment by Pankaj0038** [comment]
@pranjalipilankar update about your progress

**Comment by daksh1210jain** [comment]
i would like to work on this issue
under JWOC

**Comment by Pankaj0038** [comment]
@daksh1210jain its already assigned , I'm waiting for his reply 
if he cannot do it or do not update till tomorrow evening then will assign you

**Comment by pranjalipilankar** [comment]
I am almost done. Will make a pull request in an hour.

**Comment by ayushmorbar** [comment]
Hey @Pankaj0038 ,

I would like to work on this issue as part of JWoC, if it's not done yet.

**Comment by Pankaj0038** [comment]
okay @ayushmorbar but you need to do it from scratch don't use library just

**Comment by ayushmorbar** [comment]
Understood

**Comment by ayushmorbar** [comment]
#77
