### ISSUE TITLE
add text to binary encoder

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#5]
convert text to space separated 8 bit binary number string 

ascii of 'h' = 104 , 'e' = 101 , 'l' = 108 , 'o' = 111
hello --> 104,101,108,108,111 -->  01101000 01100101 01101100 01101100 01101111

**Comment by ArfaKA-03** [comment]
I would like to contribute to this project (jwoc 24)

**Comment by Pankaj0038** [comment]
Comment after the contest starts
I cannot assign you right now

**Comment by basedBaba** [comment]
Hello! I would like to work on this issue under JWOC.

**Comment by Pankaj0038** [comment]
okay @basedBaba
