### ISSUE TITLE
Create Documentation web page

### ISSUE THREAD

**Issue by Prithwi32** [Pankaj0038/dcodeKi#56]
- web page contains basic description of the tool is given with all the tech stack
- name of the contributor
- downloadable page

**Comment by Prithwi32** [comment]
I would like to work on this issue under JWOC

**Comment by Pankaj0038** [comment]
okay @Prithwi32 

1. Improve the UI of index (about) page including header , footer
2. add list of encoder/decoders
3. create download button for windows / linux and macOS
4. contributors section
5. contact section (gmail: pb2538@cse.jgec.ac.in , github: https://github.com/Pankaj0038)
