### ISSUE TITLE
Add a page on clicking symbol cipher

### ISSUE THREAD

**Issue by daksh1210jain** [Pankaj0038/dcodeKi#66]
i want that a new page is appeared when we click the symbol cipher button
under JWOC

**Comment by Pankaj0038** [comment]
Okay @daksh1210jain

**Comment by Pankaj0038** [comment]
@daksh1210jain update your progress

**Comment by daksh1210jain** [comment]
sir i am almost done but due to some health issue just finishing is left 
I will create the PR by tomorrow for sure
