### ISSUE TITLE
page is not responsive and in download section, link is not attached. I want to work on this issue

### ISSUE THREAD

**Issue by Zenitssuu** [Pankaj0038/dcodeKi#68]
website is not responsive, outline breaks for small screens
link is not added in download section and it's unattractive.
I want to work on this issue, please assign it to me under JWOC'24.
![Screenshot (227)](https://github.com/Pankaj0038/dcodeKi/assets/154405878/5972481f-98c4-4dce-af4d-17c92825734c)

**Comment by Pankaj0038** [comment]
Okay @Zenitssuu

**Comment by Pankaj0038** [comment]
@Zenitssuu update your progress
