### ISSUE TITLE
add text to hex encoder

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#7]
text message to ascii for each character and then convert the number into hexadecimal number 

ascii of 'h' = 104 , 'e' = 101 , 'l' = 108 , 'o' = 111

hello --> 104,101,108,108,111 --> 68 65 6c 6c 6f 

you can also output the numbers without spaces like 68656c6c6f

**Comment by k3s1** [comment]
I would like to work on this issue under JWOC

**Comment by Pankaj0038** [comment]
@k3s1 kindly comment after 12 AM

**Comment by basedBaba** [comment]
Hello! I would like to work on this issue under JWOC.

**Comment by Pankaj0038** [comment]
okay @basedBaba
