### ISSUE TITLE
Improve the UI of the Contact Form !

### ISSUE THREAD

**Issue by SohanRC** [Pankaj0038/dcodeKi#70]
Would like to improve the UI of the Contact Form According to the given screenshot below ! Would change the colours so that it looks good according to the given website ! Please assign me under JWOC 2024.

![Responsive-Contact-Form](https://github.com/Pankaj0038/dcodeKi/assets/124901633/a22124d0-a8a7-4d90-a068-2233a92212e9)

**Comment by Pankaj0038** [comment]
Okay @SohanRC

**Comment by Pankaj0038** [comment]
@SohanRC update about your progress
