### ISSUE TITLE
Add One-Time Pad Encoder-Decoder

### ISSUE THREAD

**Issue by ayushmorbar** [Pankaj0038/dcodeKi#79]
Enhance the tool's encryption capabilities by adding the One-Time Pad encoder-decoder. This cipher, known for its security, utilizes a key as long as the message.

### References
- [One-Time Pad](https://en.wikipedia.org/wiki/One-time_pad)

**Comment by Pankaj0038** [comment]
Okay go for it @ayushmorbar

**Comment by ayushmorbar** [comment]
Hey,
Can you unassigned me from this issue for now ~ I've tried almost 6 hours on this but I am not able to fix the errors as it keeps on coming and the program works great for some cases. Until then do assign me the other issue! I'll get on this as soon as I grasp the errors!

**Comment by Pankaj0038** [comment]
Okay @ayushmorbar
