### ISSUE TITLE
add XOR encoder/decoder 

### ISSUE THREAD

**Issue by Pankaj0038** [Pankaj0038/dcodeKi#8]
while adding xor encoder you need to add a input field to get the key
first convert each character to binary
input = hello
key = 1
hello --> 104,101,108,108,111 --> 01101000 , 01100101 , 01101100 , 01101100 , 01101111
then xor the key value with each of the binary
suppose my key = 1
then 01101000 xor 00000001 = 01101001 = 105 = i
01100101 xor 00000001 = 01100100 = 100 = d
01101100 xor 00000001 = 01101101 = 109 = m
01101100 xor 00000001 = 01101101 = 109 = m
01101111 xor 00000001 = 01101110 = 110 = n

output = idmmn

**Comment by SGCODEX** [comment]
Sir, I would like to work on this issue under JWOC

**Comment by Pankaj0038** [comment]
okay @SGCODEX

**Comment by SGCODEX** [comment]
Thank you sir, Altho I had built an encoder-decoder of myself too once, I can open a new issue after this, for new type of encryptions sir?

**Comment by Pankaj0038** [comment]
@SGCODEX yes you can

**Comment by Pankaj0038** [comment]
@SGCODEX sorry for the inconvenience but as I removed the mandatory condition of input field I'm reducing the difficulty level to medium 

Also added another issue related to the key input field you can contribute in it to gain more score

**Comment by SGCODEX** [comment]
Bhaiya, kaunsa mandatory condition??
Ahh 🥲, I was almost done with that space approach for text<space>numerical key. But no issues, I will modify the code, .... But where do we take the key value now?

**Comment by Pankaj0038** [comment]
no need to worry about that
you take it space separated way when the input field will be done I'll modify all the code or may generate another issue regarding this

**Comment by SGCODEX** [comment]
Okay bhaiya
