### ISSUE TITLE
Implement Gray Code Encoder-Decoder

### ISSUE THREAD

**Issue by ayushmorbar** [Pankaj0038/dcodeKi#80]
Introduce Gray Code functionality to the encoder-decoder tool. Gray Code is a binary system where adjacent values differ in only one bit.

Tasks include implementing both encoding and decoding, GUI integration, documentation update, and testing.

### Expected Outcome:
Users can encode and decode binary sequences using Gray Code representation.

### Note to Contributors:
Binary operations expertise is essential. Collaborate for an efficient solution.

### Reference:
- [Gray Code](https://en.wikipedia.org/wiki/Gray_code)

**Comment by ayushmorbar** [comment]
I would like to take on this Issue as part of JWoC. 🙋🏻‍♂️

**Comment by Pankaj0038** [comment]
Complete the other task first
