### ISSUE TITLE
Add ASCII Encoder-Decoder

### ISSUE THREAD

**Issue by ayushmorbar** [Pankaj0038/dcodeKi#82]
Integrate ASCII encoder-decoder functions where users can input plain text for encoding or ASCII text for decoding.

**Comment by ayushmorbar** [comment]
I am up for this, issue.

**Comment by Pankaj0038** [comment]
@ayushmorbar you can do that but I cannot give you score for that

**Comment by ayushmorbar** [comment]
yeah, it's okay~ I still want to do it anyways

**Comment by Pankaj0038** [comment]
okay @ayushmorbar go for it

**Comment by ayushmorbar** [comment]
DONE.

**Comment by ayushmorbar** [comment]
@Pankaj0038 done.
